# Generated by Django 3.2.9 on 2021-12-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='MenuElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('ingredients', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Cold Drink', 'Cold Drink'), ('Hot Drink', 'Hot Drink'), ('Alcohol', 'Alcohol'), ('Starter', 'Starter'), ('Meat&Fish', 'Meat&Fish'), ('Soup', 'Soup'), ('Burger', 'Burger'), ('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Desert', 'Desert')], max_length=100, null=True)),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.restaurant'),
        ),
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('rate', models.DecimalField(decimal_places=1, default=10, max_digits=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.restaurant')),
            ],
        ),
    ]
