# Generated by Django 4.0 on 2021-12-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Cafe', 'Cafe'), ('Bar', 'Bar'), ('Fine Dining', 'Fine Dining'), ('Casual or Family-Style', 'Casual or Family-Style'), ('Fast Food', 'Fast Food'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
