# Generated by Django 3.2.9 on 2021-11-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
