# Generated by Django 3.2.9 on 2021-12-20 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_id_comment_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_id',
            new_name='id',
        ),
    ]
