# Generated by Django 3.2.9 on 2021-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuelement',
            name='image',
            field=models.ImageField(default='default.png', upload_to='menu'),
        ),
    ]
