# Generated by Django 3.2.9 on 2021-12-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211218_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuelement',
            old_name='res',
            new_name='menu',
        ),
        migrations.AlterField(
            model_name='order',
            name='content',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
