# Generated by Django 3.2.9 on 2021-12-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211218_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
