# Generated by Django 3.2.9 on 2021-12-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211219_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
